[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
revert_strings = "default"

# Remappings for Chainlink contracts
remappings = [
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "@chainlink/contracts-ccip/=lib/chainlink/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

# RPC endpoints for different networks
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
polygon_mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"
arbitrum_goerli = "https://arbitrum-goerli.infura.io/v3/${INFURA_API_KEY}"
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
